<a href="https://colab.research.google.com/github/FMularski/DataScienceBootcamp/blob/master/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.18.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [5]:
x = np.array([1, 3])
x

array([1, 3])

In [6]:
print(x)

[1 3]


In [7]:
type(x)

numpy.ndarray

In [8]:
x.ndim

1

In [9]:
x.shape

(2,)

In [10]:
x.size

2

In [11]:
x.dtype

dtype('int64')

In [14]:
x = np.array([1.2, 3.4, 4.4])
x

array([1.2, 3.4, 4.4])

In [15]:
x.ndim

1

In [16]:
x.dtype

dtype('float64')

In [17]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [18]:
x.ndim

2

In [19]:
x.shape

(2, 2)

In [21]:
x = np.array([[1, 2, 4], [4, 2, 1]])
x

array([[1, 2, 4],
       [4, 2, 1]])

In [22]:
x = np.array([
              [[4, 3, 1], [4, 3, 2]],
              [[6, 3, 0], [1, 2, 2]]
              ])
x

array([[[4, 3, 1],
        [4, 3, 2]],

       [[6, 3, 0],
        [1, 2, 2]]])

In [23]:
x.shape

(2, 2, 3)

In [24]:
A = np.array([1, 2, 3], dtype='float')
A

array([1., 2., 3.])