<a href="https://colab.research.google.com/github/FMularski/DataScienceBootcamp/blob/master/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
# normalizacja wektora
v = np.array([5, 2])
n_v = np.sqrt(v[0]**2 + v[1]**2)
print(n_v)

n_v = np.linalg.norm(v)
print(n_v)

5.385164807134504
5.385164807134504


In [6]:
# cd
v = np.array([5, -3 , 1])
n_v = np.linalg.norm(v)
print(n_v)

5.916079783099616


In [12]:
# odleglosc punktow w przestrzeni
p = np.array([3, 0, 5])
q = np.array([0, 4, -1])

sum = 0
for cordp, cordq in zip(p, q):
  sum += (cordp - cordq)**2 
result = np.sqrt(sum)
print(result)


7.810249675906654


In [13]:
result = np.linalg.norm(p - q)   # p - q to wektor od q do p, jego dlugosc to odleglosc tych punktow
print(result)

7.810249675906654


In [19]:
# mnozenie macierzy
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])

Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [20]:
# wyznacznik macierzy
A = np.array([[2, 4], [-1, 3]])
np.linalg.det(A)

9.999999999999998

In [21]:
# slad macierzy ( suma elementow na przekatnej)
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

In [24]:
# macierz jednostkowa
np.eye(4, dtype='int')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [28]:
# macierz odwrotna ( tylko macierze kwadratowe)
np.set_printoptions(precision=4, suppress=True)

A = np.array([[2, 4], [-1, 3]])
A_inv = np.linalg.inv(A)
print(A)

I = np.dot(A, A_inv)
I

[[ 2  4]
 [-1  3]]


array([[1., 0.],
       [0., 1.]])

In [32]:
# macierz transponowana
A = np.array([[2, 4], [-1, 3]])
print(A.T)
np.transpose(A)

[[ 2 -1]
 [ 4  3]]


array([[ 2, -1],
       [ 4,  3]])

In [35]:
# rozwiazywanie rownan
# 2x + 4y = 10
# x - y = -1

A = np.array([[2, 4], [1, -1]])
B = np.array([[10], [-1]])

X = np.dot(np.linalg.inv(A), B)
X

array([[1.],
       [2.]])